# Generated by Django 3.1.2 on 2020-10-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Time_Created', models.DateTimeField(auto_now_add=True)),
                ('Publisher', models.CharField(max_length=200)),
                ('Tags', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_Id', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200)),
                ('Time_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
