# Generated by Django 3.1.2 on 2020-10-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag_Id',
            new_name='tag_id',
        ),
    ]
