# Generated by Django 3.1.2 on 2020-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_api', '0002_auto_20201009_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
